version: "3.8"
services:
  web-application:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./web-application/src:/usr/src/app/src
      - /usr/src/app/node_modules
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
